# Default configuration for runexperiment
# Values here are merged into CLI args if not provided explicitly.
sbatch:
  time: "01:00:00"
  mem: "4G"
  cpus-per-task: "1"
expdir: "./output"
targetdir: "./results"
