# Default configuration for runexperiment
# Values here are merged into CLI args if not provided explicitly.
sbatch:
  time: "01:00:00" # Add more SLURM options here
expdir: "./output"
targetdir: "./results"
sbatch_commands_per_task: 1 #Allows to merge multiple tasks into a single slurm task run
